package p20172;
/* CVS $Id: $ */
 
import org.apache.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from Animals.rdf 
 * @author Auto-generated by schemagen on 21 oct 2017 01:20 
 */
public class Animals {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static final Model M_MODEL = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "https://www.anims.fake/animal#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     * @return namespace as String
     * @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = M_MODEL.createResource( NS );
    
    public static final Property belongs = M_MODEL.createProperty( "https://www.anims.fake/animal#belongs" );
    
    public static final Property eat = M_MODEL.createProperty( "https://www.anims.fake/animal#eat" );
    
    public static final Property eatenBy = M_MODEL.createProperty( "https://www.anims.fake/animal#eatenBy" );
    
    public static final Property family_sibling = M_MODEL.createProperty( "https://www.anims.fake/animal#family_sibling" );
    
    public static final Property hasLegs = M_MODEL.createProperty( "https://www.anims.fake/animal#hasLegs" );
    
    public static final Property hasWings = M_MODEL.createProperty( "https://www.anims.fake/animal#hasWings" );
    
    public static final Property name = M_MODEL.createProperty( "https://www.anims.fake/animal#name" );
    
    public static final Property shareHabitat = M_MODEL.createProperty( "https://www.anims.fake/animal#shareHabitat" );
    
}
