# Families info

PREFIX ontology: <http://www.semanticweb.org/SemanticWeb_UCaldas/2017-2/ontologies/GameOfThrones#>
PREFIX schema: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX syntax: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
SELECT *
WHERE {
	?family syntax:type ontology:Family.
	?family ontology:Name ?familyName.
	?family ontology:Slogan ?slogan.

	OPTIONAL { ?p syntax:type ontology:Person.
		?p ontology:IsMember ?family.
		?p ontology:Name ?personName. }
}

