# Organizations info

PREFIX ontology: <http://www.semanticweb.org/SemanticWeb_UCaldas/2017-2/ontologies/GameOfThrones#>
PREFIX schema: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX syntax: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
SELECT *
WHERE {
	?organization syntax:type ontology:Organization.
	?organization ontology:Name ?organizationName.

	OPTIONAL { ?p syntax:type ontology:Person.
		?p ontology:IsMember ?organization.
		?p ontology:Name ?personName. }

	OPTIONAL { ?p syntax:type ontology:Person.
		?organization ontology:HasMember ?p.
		?p ontology:Name ?personName. }
}

