PREFIX ontology: <http://www.semanticweb.org/SemanticWeb_UCaldas/2017-2/ontologies/GameOfThrones#>
PREFIX schema: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX syntax: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?x ?y ?z
WHERE {
	?x ?y ?z.
}

